import Foundation

@main
struct CoreLogicTests {
    static func main() throws {
        let engine = TriggerEngine()
        assert(engine.handle(.character(":")) == .updated(.emoji, ""))
        assert(engine.handle(.character("s")) == .updated(.emoji, "s"))
        assert(engine.handle(.character("m")) == .updated(.emoji, "sm"))
        assert(engine.typedLength == 3)
        assert(engine.handle(.backspace) == .updated(.emoji, "s"))
        assert(engine.handle(.escape) == .cancelled(consume: true))
        assert(!engine.isActive)
        assert(engine.handle(.character(":")) == .updated(.emoji, ""))
        assert(engine.handle(.backspace) == .cancelled(consume: false))
        assert(engine.handle(.character(":")) == .updated(.emoji, ""))
        assert(engine.handle(.character("/")) == .cancelled(consume: false))
        assert(engine.handle(.character("/")) == .updated(.snippet, ""))
        assert(engine.handle(.character("E")) == .updated(.snippet, "e"))
        assert(engine.typedLength == 2)
        assert(engine.handle(.enter) == .accept)
        assert(engine.handle(.left) == .navigateHorizontal(-1))
        assert(engine.handle(.right) == .navigateHorizontal(1))
        engine.reset()
        assert(engine.typedLength == 0)

        let data = try Data(contentsOf: URL(fileURLWithPath: "Ogma/Resources/emoji.json"))
        let items = try JSONDecoder().decode([EmojiItem].self, from: data)
        let search = EmojiSearchService(items: items)
        assert(items.count >= 3900)
        assert(search.search("smile").first?.emoji == "😊")
        assert(search.search("coffee").first?.emoji == "☕")
        assert(search.search("cofee").first?.emoji == "☕")
        assert(search.search("dog").first?.emoji == "🐶")
        assert(search.search("party").count <= 8)
        assert(search.search("joy", limit: 40).map(\.emoji).contains("🤣"))
        assert(search.search("").count == 8)
        assert(search.search("", limit: items.count).count == items.count)

        let directory = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: directory) }
        let fileURL = directory.appendingPathComponent("snippets.json")
        let store = SnippetStore(fileURL: fileURL)
        try store.save(trigger: "Email", replacement: "hello@example.com")
        try store.save(trigger: "signature", replacement: "Best,\nTeam")
        assert(store.snippets.count == 2)
        assert(SnippetStore(fileURL: fileURL).snippets.contains { $0.replacement == "Best,\nTeam" })
        assert((try? store.save(trigger: "EMAIL", replacement: "duplicate")) == nil)
        let snippetSearch = SnippetSearchService()
        assert(snippetSearch.search("em", in: store.snippets).first?.replacement == "hello@example.com")
        assert(store.validationError(trigger: "date", replacement: "fixed") == .reservedTrigger)
        assert(SuggestionItem.date.title == "/date")
        assert(SuggestionItem.date.insertionText.hasSuffix(" "))
        assert(SuggestionItem.emoji(items[0]).insertionText == items[0].emoji + " ")
        let spaced = TextSnippet(id: UUID(), trigger: "space", replacement: "Hello ", isEnabled: true)
        assert(SuggestionItem.snippet(spaced).insertionText == "Hello ")
        let multiline = TextSnippet(id: UUID(), trigger: "line", replacement: "Hello\n", isEnabled: true)
        assert(SuggestionItem.snippet(multiline).insertionText == "Hello\n")
        let testDate = Date(timeIntervalSince1970: 12 * 60 * 60)
        assert(DateDisplayFormat.iso8601.display(testDate) == "1970-01-01")
        let email = store.snippets.first { $0.trigger == "email" }!
        try store.setEnabled(false, for: email.id)
        assert(snippetSearch.search("em", in: store.snippets).isEmpty)
        try store.save(id: email.id, trigger: "contact", replacement: "new@example.com")
        assert(SnippetStore(fileURL: fileURL).snippets.contains { $0.trigger == "contact" && !$0.isEnabled })
        try store.delete(email.id)
        assert(SnippetStore(fileURL: fileURL).snippets.count == 1)
        print("Core logic tests passed")
    }
}
